server:
  port: 8006
spring:
  application:
    name: provider-consul-payment8006
  cloud:
    consul:
      host: 192.168.44.100
      port: 8500
      discovery:
        service-name: ${spring.application.name}